### ISSUE TITLE
Scene Creation for JETSTRÖM works not in GUI

### ISSUE THREAD

**Issue by 3b10ae47** [sanjoyg/dirigera_platform#128]
Preface:
- The work on the integration is highly appreciated.
- App Version: 0.0.1

Description:
- Creation of Scenes is supposed to work in LIVE-MODUS (live mode in English? My HASS is set to German.), where entities can be set to the desired state and the set states are stored in the Scene. 
- For my JETSTRÖM light, I can set whatever I want. The set state for the light is always some green colour. 
- The YAML configuration mode shows, that the parameter 'color_mode' is set to `hs`, regardless what was chosen in LIVE-MODUS. `hs` is also shown two times in `suported_color_modes`, which seems weird to me.
- After changing `color_mode` to `color_temp` and setting `color_temp_kelvin` and `color_temp` to the desired values (3000 and 250 in my case) in YAML, the Scene works fine.
- After switching from YAML to GUI-Mode for Scene Creation, the Scene works fine.
- After turning on LIVE-MODUS, `color_mode` is set to `hs` and the lamp is green again. 

Workaround (in case, somebody with the same problem comes across this Issue):
- Set everything up in YAML and don't do anything in LIVE-MODUS.
- If you want to add further Entities in LIVE-MODUS, change the values for JETSTRÖM in YAML after work in LIVE-MODUS is done.

**Comment by sanjoyg** [comment]
Would you please dump json for me, that would help

**Comment by 3b10ae47** [comment]
Today I found out, that `color_temp_kelvin` seems to do nothing, only `color_temp` in mireds seems to affect the colour temperature. Here's the yaml that appears to work:
```yaml
id: "1725562932996"
name: Wohnzimmer Hell
entities:
  light.wohnzimmer_sofa:
    min_color_temp_kelvin: 2202
    max_color_temp_kelvin: 4000
    min_mireds: 250
    max_mireds: 454
    supported_color_modes:
      - color_temp
      - hs
      - hs
    color_mode: color_temp
    brightness: 255
    color_temp_kelvin: null
    color_temp: 370
    hs_color:
      - 132
      - 34
    rgb_color:
      - 168
      - 255
      - 186
    xy_color:
      - 0.267
      - 0.433
    friendly_name: Wohnzimmer Sofa
    supported_features: 0
    state: "on"
metadata:
  light.wohnzimmer_sofa:
    entity_only: true
```
I guess, the other colour definitions could be removed, i.e. `hs_color`, `rgb_color` and `xy_color`, but I didn't test, which parameters are really needed in the configuration.
