### ISSUE TITLE
Plugin stops working every day aroun 08:30 AM

### ISSUE THREAD

**Issue by N-Hertstein** [sanjoyg/dirigera_platform#134]
Weird issue.
Every day around 8:30 AM the integrations stops working. I'm unable to change states of lights and plugs (all tradfri, have had them for a while), motion sensors no longer show if motion was triggered (also tradfri).

I can fix it by reloading the hub and waiting for a bit but that's not really great. Reloading the config does not work as I tried the following automation:

```
id: '1738085376426'
alias: Reload IKEA Dirigera
description: ''
triggers:
  - trigger: time
    at: '00:00:00'
  - trigger: time
    at: '12:00:00'
conditions: []
actions:
  - action: homeassistant.reload_config_entry
    metadata: {}
    data: {}
    target:
      device_id: ffcb88abd14a36f768e187f8a646a91b
mode: single
```

I also attempted manually triggering this automation when things stopped functioning today.
I have to manually reload the hub as shown below every day.

![Image](https://github.com/user-attachments/assets/c076f938-9a0e-4b79-a405-397739ae8ede)

Currently I am unable to dump data as it gives an error. Will update if that changes.
